        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 18 17:41:23 2014
        MODULE CPP_WRITE_LINE__genmod
          INTERFACE 
            SUBROUTINE CPP_WRITE_LINE(LINE)
              CHARACTER(LEN=256), INTENT(IN) :: LINE
            END SUBROUTINE CPP_WRITE_LINE
          END INTERFACE 
        END MODULE CPP_WRITE_LINE__genmod
