        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 19 16:25:24 2014
        MODULE DIWO_CONTINUE_BUILD_NOT_E_OR_P__genmod
          INTERFACE 
            FUNCTION DIWO_CONTINUE_BUILD_NOT_E_OR_P
              INTEGER(KIND=4) :: DIWO_CONTINUE_BUILD_NOT_E_OR_P
            END FUNCTION DIWO_CONTINUE_BUILD_NOT_E_OR_P
          END INTERFACE 
        END MODULE DIWO_CONTINUE_BUILD_NOT_E_OR_P__genmod
