        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 18 17:41:23 2014
        MODULE CPP_READ_LINE__genmod
          INTERFACE 
            SUBROUTINE CPP_READ_LINE(LINE,COUNT)
              CHARACTER(LEN=256), INTENT(OUT) :: LINE
              INTEGER(KIND=4), INTENT(OUT) :: COUNT
            END SUBROUTINE CPP_READ_LINE
          END INTERFACE 
        END MODULE CPP_READ_LINE__genmod
