        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 19 16:25:24 2014
        MODULE DIWO_START_BUILD__genmod
          INTERFACE 
            FUNCTION DIWO_START_BUILD(NAME_IN,NAME_IN_LEN,OUT_NAME,     &
     &OUT_NAME_LEN)
              CHARACTER(LEN=256), INTENT(IN) :: NAME_IN
              INTEGER(KIND=4), INTENT(IN) :: NAME_IN_LEN
              CHARACTER(LEN=256), INTENT(OUT) :: OUT_NAME
              INTEGER(KIND=4), INTENT(OUT) :: OUT_NAME_LEN
              INTEGER(KIND=4) :: DIWO_START_BUILD
            END FUNCTION DIWO_START_BUILD
          END INTERFACE 
        END MODULE DIWO_START_BUILD__genmod
